### ISSUE TITLE
感觉界面和功能与 Octotree 这个插件基本一样啊

### ISSUE THREAD

**Issue by Chuck-Ray** [ineo6/git-master#1]
是fork过来去掉账户做的中文化么？

**Comment by ineo6** [comment]
目前主要功能是和`Octotree`一致的，在此基础上支持了`GitLab`，`Gitee`，也整合了一些其他功能，比如`GitHub`通知，仓库大小信息展示等。我弄这个的初衷是整合比较更多功能，也会添加`Octotree`里的功能。

如果你使用`GitHub`，以及更关注树形展示功能，`GItMaster`比不上`Octotree`，账户功能以及登录后新增的功能并未开源出来。

**Comment by geekyouth** [comment]
> 目前主要功能是和`Octotree`一致的，在此基础上支持了`GitLab`，`Gitee`，也整合了一些其他功能，比如`GitHub`通知，仓库大小信息展示等。我弄这个的初衷是整合比较更多功能，也会添加`Octotree`里的功能。
> 
> 如果你使用`GitHub`，以及更关注树形展示功能，`GItMaster`比不上`Octotree`，账户功能以及登录后新增的功能并未开源出来。

---
这个插件很棒，我试过几乎所有的 codetree 插件，都无法完全适配 3大主流仓库，然后你做到了。谢谢，已加星✨🤞

**Comment by m666m** [comment]
不错啊，我现在用edge，没找到octotree的插件，才找到这个插件的，好用，希望持续改进做下去

**Comment by pic4xiu** [comment]
Thanks,this plug-in is enough for me ,but why does the download function filter out exe and doc.Hope to improve😊

**Comment by 2240726829** [comment]
很不错，希望能分享给更多的人！
