### ISSUE TITLE
想问下可以加下支持Gogs吗。现在会识别成github填了令牌貌似没用

### ISSUE THREAD

**Issue by David2k13** [ineo6/git-master#10]
想问下可以加下支持Gogs吗。现在会识别成github填了令牌貌似没用

**Comment by ineo6** [comment]
可以考虑下，目前还有其他功能正在处理。

**Comment by David2k13** [comment]
> 可以考虑下，目前还有其他功能正在处理。

谢谢

**Comment by gclm** [comment]
还有 gogs 的姐妹版 gitea, 我们用的是 gitea

**Comment by ineo6** [comment]
收到，目前没法投入对新平台的开发，抱歉，只能说尽早。

**Comment by ineo6** [comment]
> 还有 gogs 的姐妹版 gitea, 我们用的是 gitea

`gitea`现已加入套餐，欢迎试用下（1.9.0版本）。

**Comment by David2k13** [comment]
> > 还有 gogs 的姐妹版 gitea, 我们用的是 gitea
> 
> `gitea`现已加入套餐，欢迎试用下（1.9.0版本）。

棒棒哒，支持一下，已经换公司了不用gogs了

**Comment by roberChen** [comment]
已搭配自搭gitea使用, 感觉很有精神! 过来赞一个!

**Comment by ineo6** [comment]
如果使用中遇到问题，欢迎反馈，我们一起完善扩展。
