### ISSUE TITLE
希望支持 gitlab 的 subgroup 功能

### ISSUE THREAD

**Issue by BoltDoggy** [ineo6/git-master#11]
普通的项目路径为 https://git.xxx.com/aaa/bbb, 其中 aaa 为 group, bbb 为 project

在 gitlab 中支持创建 subgrroup, 如 https://git.xxx.com/aaa/bbb/ccc, 其中 aaa 为 group, bbb 为 subgroup, ccc 为 project.

这时, git-master 会识别为 bbb 为 project. 

访问文件路径 https://git.xxx.com/aaa/bbb/ccc/blob/master/README.md 会打开 https://git.xxx.com/aaa/bbb/blob/master/README.md 出现 404

**Comment by popeyelau** [comment]
https://github.com/ineo6/git-master/issues/20#issuecomment-653727068

**Comment by ineo6** [comment]
`1.11.0`开始支持`GitLab`多级目录接口，可以尝试下，遇到问题欢迎反馈。
