### ISSUE TITLE
插件图标的问号是一直都会有吗

### ISSUE THREAD

**Issue by kvkboy** [ineo6/git-master#12]
浏览器是edge

**Comment by kvkboy** [comment]
![image](https://user-images.githubusercontent.com/30861318/83097334-71c0d900-a0da-11ea-8306-ce0e72d49a2e.png)

**Comment by ineo6** [comment]
问号的状态指的是`GitHub`通知没有配置，不影响其他功能，下个版本会取消这里的状态显示。
