### ISSUE TITLE
【新功能】希望能显示每个文件夹下的文件数量

### ISSUE THREAD

**Issue by ZhangYue-vhyt** [ineo6/git-master#13]
RT

**Comment by ineo6** [comment]
希望在哪个位置展示呢？

**Comment by ZhangYue-vhyt** [comment]
展示在这里吧，如果是文件夹就显示子文件数量和总大小，如果是文件就显示文件大小。这个功能其他的同类插件都没有。

![image](https://user-images.githubusercontent.com/9450184/83369276-cccc2780-a389-11ea-9de1-e435a86dd595.png)

**Comment by ineo6** [comment]
已加入`1.5.x`套餐

**Comment by ZhangYue-vhyt** [comment]
已更新，非常棒！希望后续对于文件夹可以显示其目录下的对象数量。Github 网页对于单个文件夹下的预览上限是1000个，超过这个数量就不显示了。但其界面又不显示当前文件夹下有多少文件，有时候不小心就上传的超过数量限制。

**Comment by ineo6** [comment]
目前在树里面已经显示了文件数量了，是我没有理解你说的吗？

**Comment by ZhangYue-vhyt** [comment]
是我这边有什么问题吗？

![image](https://user-images.githubusercontent.com/9450184/85378439-8db47080-b508-11ea-8615-08800b6fee21.png)
![image](https://user-images.githubusercontent.com/9450184/85378471-99079c00-b508-11ea-9df7-abb4326cc49e.png)

**Comment by ineo6** [comment]
我知道了，`lazyload`是无法提前知道文件夹数量的。

现在是获取到所有文件后，收集文件数量的。用到的获取文件接口也没有底下的文件数量信息。

只能再找下补充方案来支持`lazyload`了。

**Comment by ineo6** [comment]
我知道了，`lazyload`是无法提前知道文件夹数量的。

现在是获取到所有文件后，收集文件数量的。用到的获取文件接口也没有底下的文件数量信息。

只能再找下补充方案来支持`lazyload`了。

**Comment by ZhangYue-vhyt** [comment]
好的，我关闭了 `lazyload`，现在成功显示了，谢谢！
