### ISSUE TITLE
功能预览下的布局有问题

### ISSUE THREAD

**Issue by yzy8366** [ineo6/git-master#14]
### 开启GitHub的预览功能后布局显示有问题如图
<img width="1016" alt="5525A9EC-005E-409D-8C3C-A1C11BD4D2F2" src="https://user-images.githubusercontent.com/23303336/85092142-aa585c00-b21b-11ea-93bc-551813c879a5.png">
<img width="1377" alt="8AAF6230-005A-40ED-AD4A-2FA726E146AE" src="https://user-images.githubusercontent.com/23303336/85092156-b17f6a00-b21b-11ea-86d5-c2bcee007eb0.png">

**Comment by ineo6** [comment]
Thanks. 已经确认了这个问题。

**Comment by ineo6** [comment]
fixed
