### ISSUE TITLE
文件下载功能

### ISSUE THREAD

**Issue by wolffy1998** [ineo6/git-master#18]
作者可以添加像谷歌商店的GitZip下载单个文件的功能吗？或者是多选文件下载而不是一次性把仓库文件全部下载下来

**Comment by ineo6** [comment]
因为`GitHub`界面调整，之前的代码无效导致看不到文件下载功能，新的版本正在审核中（Edge），Chrome已发布。

目前支持的是单个文件，单个文件夹的下载。你提到的`GitZip`，我会看下有哪些功能可以加进来。

**Comment by ineo6** [comment]
最新版单个文件支持直接点击下载。`GitZip`的调研会在后续进行。
