### ISSUE TITLE
查看原始文件功能无法使用

### ISSUE THREAD

**Issue by geekyouth** [ineo6/git-master#2]
# https://github.com/DTStack/flinkx/
![image](https://user-images.githubusercontent.com/12899262/78777298-e07f9100-79cb-11ea-90d4-6b19a57d7ec0.png)

你的跳转逻辑是不是有点问题？

**Comment by ineo6** [comment]
我这边自己尝试了下没有复现，能提供下复现步骤吗？另外附上Chome版本，以及操作系统。

**Comment by ineo6** [comment]
目前可以临时禁用懒加载功能解决，下次发布即可解决。

**Comment by ineo6** [comment]
`v1.2.0` fixed

**Comment by geekyouth** [comment]
bug 重现，gitlab 从代码结构树边栏打开的文件，路径不对。

**Comment by ineo6** [comment]
404页面？目前不支持多级分组下的项目显示，看下是否是这个问题。
