### ISSUE TITLE
如何配置gitlab 私有化部署的地址

### ISSUE THREAD

**Issue by wangtaicheng** [ineo6/git-master#20]
如何配置gitlab 私有化部署的地址，如果gitlab 为本地部署，如何更改地址？

**Comment by ineo6** [comment]
点击插件图标，点击启动GitLab。

![image](https://user-images.githubusercontent.com/3783838/86306215-40da4380-bc46-11ea-9a64-07b049bdc410.png)

**Comment by wangtaicheng** [comment]
看到了

**Comment by popeyelau** [comment]
![image](https://user-images.githubusercontent.com/6114544/86506242-38c60380-be00-11ea-911d-f53e65ab4239.png)
@ineo6 
目录树中的文件地址错误，请问如何配置？

**Comment by ineo6** [comment]
@popeyelau 我看你的仓库是属于多级分组的吧，目前判断这个比较复杂，还没支持多级分组。

**Comment by zhangchenna** [comment]
同求此功能 gitlab遇到无法识别
