### ISSUE TITLE
希望支持 gogs

### ISSUE THREAD

**Issue by sbilly** [ineo6/git-master#21]
[gogs]( https://gogs.io/) 也是一个不错的代码库，希望能支持。

[DEMO](https://try.gogs.io/)

![](https://gogs.io/img/screenshots/2.png)

**Comment by ilaipi** [comment]
还真有这样的issue，不知道能不能支持 @ineo6

**Comment by ineo6** [comment]
之前简单调研过，好像`api`不一定能满足。我重新再看下。

**Comment by ilaipi** [comment]
@ineo6 感谢！

**Comment by ineo6** [comment]
Update：目前看最新版的`api`是支持基本的树结构浏览（懒加载），稍微空点的时候会准备下发布。

**Comment by ilaipi** [comment]
> Update：目前看最新版的`api`是支持基本的树结构浏览（懒加载），稍微空点的时候会准备下发布。

非常感谢~自建的，公司自己域名的，应该也能用吧？

**Comment by ineo6** [comment]
> > Update：目前看最新版的`api`是支持基本的树结构浏览（懒加载），稍微空点的时候会准备下发布。
> 
> 非常感谢~自建的，公司自己域名的，应该也能用吧？

支持的，不过对版本有要求，我是用官网`demo`站点测试的，具体哪些版本能用还不好说。

**Comment by ilaipi** [comment]
> > > Update：目前看最新版的`api`是支持基本的树结构浏览（懒加载），稍微空点的时候会准备下发布。
> > 
> > 
> > 非常感谢~自建的，公司自己域名的，应该也能用吧？
> 
> 支持的，不过对版本有要求，我是用官网`demo`站点测试的，具体哪些版本能用还不好说。

嗯嗯，我是最近才搭建的服务，是最新版的。其它版本的到时候如果有其它用户可以看看反馈

**Comment by ineo6** [comment]
`Firefox`和`Chrome`最新版（1.16.0）已支持`gogs`，`Edge`还在路上。

**Comment by ilaipi** [comment]
体验了一下，我是edge，不过已经更新到1.16.0了，应该是edge装的是chrome版插件。目录下面的文件显示不出来

![image](https://user-images.githubusercontent.com/1689135/129516564-8c923de9-139c-4bee-bbca-c9754d1dfbdf.png)

**Comment by ineo6** [comment]
现有`api`只能实现`lazy load`效果，另外这次没有没有强制开启，所以暂时需要手动设置下。

**Comment by ilaipi** [comment]
> 现有`api`只能实现`lazy load`效果，另外这次没有没有强制开启，所以暂时需要手动设置下。

开启之后可以正常用了，谢谢！
