### ISSUE TITLE
[BUG] 点击单个文件下载按钮控制台报错

### ISSUE THREAD

**Issue by roojay520** [ineo6/git-master#23]
看起来是像触发了 github 的同源策略
SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.

<img width="1611" alt="git-master-error" src="https://user-images.githubusercontent.com/11495164/87277718-67855d80-c515-11ea-8c7f-b4efb77441fe.png">

**Comment by ineo6** [comment]
浏览器是否有什么特殊设置呢，比如禁用了权限，隐身模式之类的？目前看是浏览器给与插件的权限不够。我尝试了一些操作没有复现。

提供下浏览器和版本号，电脑系统。

**Comment by roojay520** [comment]
Chrome Version: 83.0.4103.116（正式版本） （64 位）
OS: macOS Mojave 版本10.14.6

浏览器没做什么特殊权限限制, 正常模式下使用

**Comment by roojay520** [comment]
我把项目拉取下来打包直接跑可以下载, 但是安装应用商店的扩展应用点击下载就直接跳到了 https://raw.githubusercontent.com/ineo6/git-master/master/.prettierrc.js 这个资源链接.

经过测试应该是 a 标签的 download 属性在非同源情况下失效了, 导致直接跳转到资源页面产生的报错

**Comment by ineo6** [comment]
@roojay520 这个是因为`chrome`和`edge`还不是最新支持直接下载的代码，会稍后发布上去。

**Comment by ineo6** [comment]
`1.8.0`版本已修复
