### ISSUE TITLE
[BUG]Github错误页面中，文件树显示重叠

### ISSUE THREAD

**Issue by ssxwcz** [ineo6/git-master#24]
![Snipaste_2020-07-13_15-00-50](https://user-images.githubusercontent.com/43665491/87279353-13c94300-c51a-11ea-917c-4c38f92b8ce9.png)

![Snipaste_2020-07-13_15-00-57](https://user-images.githubusercontent.com/43665491/87279391-73bfe980-c51a-11ea-8ff6-4395d3686ebb.png)

**Comment by ineo6** [comment]
Thanks, 已确认。
