### ISSUE TITLE
目录层级问题

### ISSUE THREAD

**Issue by zicai1026** [ineo6/git-master#25]
遇到目录多的项目就是这种
![QQ截图20200716173824](https://user-images.githubusercontent.com/8031864/87655824-4b8af180-c78b-11ea-920d-b8a957ae130c.png)
能不能把目录展示成这样
```
provider-sample
    src/main
        java
           org/apache/dubbo/spring/boot/sample/provider
               bootstrap
                   xxx.java
               service
                   xxx.java
        resources
```

**Comment by ineo6** [comment]
你启用了`lazyload`，启用之后是无法提前知道这样的情况的，关掉后是支持的。

**Comment by zicai1026** [comment]
> 你启用了`lazyload`，启用之后是无法提前知道这样的情况的，关掉后是支持的。
这样啊，我说这层级看着这么深，点进去都晕了
谢谢解答
