### ISSUE TITLE
[BUG] lib/lib.xxx.d.ts file link incorrect in github.com/microsoft/TypeScript

### ISSUE THREAD

**Issue by sorcererxw** [ineo6/git-master#26]
The correct file url is `https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.promise.d.ts`.
But the link GitMaster provides is `https://github.com/microsoft/TypeScript/blob/master/lib.es2015.promise.d.ts`.

**Comment by ineo6** [comment]
Thanks. Bug has been fixed and will release in next version.
