### ISSUE TITLE
点击文件后，文件树会显示一个边框

### ISSUE THREAD

**Issue by ssxwcz** [ineo6/git-master#27]
点击一个文件后，文件树上会显现出一个黑色边框，这个边框能否去除？
![image](https://user-images.githubusercontent.com/43665491/88246943-aa41f500-ccce-11ea-8531-1b51d629899c.png)

**Comment by ineo6** [comment]
已确认并修复，会在下一个版本修复。

**Comment by ssxwcz** [comment]
感谢作者的付出，插件体验非常好

**Comment by ineo6** [comment]
`1.9.0`已修改该问题。
