### ISSUE TITLE
能否添加一个新的短行快捷复制的功能

### ISSUE THREAD

**Issue by Xrafece** [ineo6/git-master#28]
我是一个从`Gitako`插件转过来的用户。
其他功能目前都很满意，可不可以添加一个Copy Snippet的功能，复制笔记的代码块很方便。
[Copy Snippet](https://github.com/EnixCoda/Gitako/wiki/Copy-file-and-snippet#copy-snippet)
万分感谢作者大大。

**Comment by ineo6** [comment]
收到，很好的建议，我记到小本本上了。

**Comment by ineo6** [comment]
`1.9.0`版本已发布，增加了`Copy Snippet`功能。
