### ISSUE TITLE
[BUG]团队下的项目，文件路径匹配错误，404

### ISSUE THREAD

**Issue by zobor** [ineo6/git-master#29]
场景：
如果一个项目A是放在团队G下的，A下的文件README.md文件路径会缺少项目名信息导致404
现状：/团队/分组/blob/master/README.md
正确的是：/团队/分组/项目/blob/master/README.md

**Comment by ineo6** [comment]
收到多次反馈了，正在处理该问题。

**Comment by HaoQChen** [comment]
请问这个问题有什么进展了么？

**Comment by ineo6** [comment]
前面完成了一个版本的开发，不过会影响一些正常功能的使用，所以没有在 1.9.0 里发布。

目前的难点还是在于从`url`里面，要区分“团队”、“分组”、“仓库名”、“文件名”等信息，因为没有明显的区分特征，所以会误判，导致某些功能收到影响。

接下来会再抽时间，继续专门处理下。

**Comment by HaoQChen** [comment]
> 前面完成了一个版本的开发，不过会影响一些正常功能的使用，所以没有在 1.9.0 里发布。
> 
> 目前的难点还是在于从`url`里面，要区分“团队”、“分组”、“仓库名”、“文件名”等信息，因为没有明显的区分特征，所以会误判，导致某些功能收到影响。
> 
> 接下来会再抽时间，继续专门处理下。

感觉这个功能很关键，公司的工程都在group下的～～

话说整这个插件都需要哪些知识，有没有系统教程之类的

**Comment by ineo6** [comment]
@zobor @HaoQChen `1.11.0`开始支持`GitLab`多级目录接口，可以尝试下，遇到问题欢迎反馈。

**Comment by zobor** [comment]
> @zobor @HaoQChen `1.11.0`开始支持`GitLab`多级目录接口，可以尝试下，遇到问题欢迎反馈。

非常感谢，可以用了

**Comment by HaoQChen** [comment]
我貌似还有点问题

真实目录是：`http://192.168.1.20/system_codebase/factory_tool/mech/absdist_horiz_calibration/blob/master/.clang-format`

但git master出来的是`http://192.168.1.20/system_codebase/factory_tool/mech/blob/master/.clang-format`

`absdist_horiz_calibration`是我的工程名

![image](https://user-images.githubusercontent.com/13584792/93839107-6ebbab00-fcbe-11ea-9017-63102814d7fd.png)

@ineo6

**Comment by HaoQChen** [comment]
有些工程又是可以的，是限制了group的深度吗？

**Comment by ineo6** [comment]
应该是逻辑还有点问题，我看下。

**Comment by ineo6** [comment]
可以单独提一个`issue`追踪下。

**Comment by HaoQChen** [comment]
group是3层的都不太行
