### ISSUE TITLE
Wrong URLs in tree sidebar

### ISSUE THREAD

**Issue by rdeago** [ineo6/git-master#3]
URLs in the tree sidebar links do not contain a file's path. It is like all files were in a repo's root.

**To reproduce:**

- Open https://github.com/ineo6/git-master/ with GitMaster active.
- Open the sidebar.
- Click on the `views` folder.
- Click on `inject.js`.
- Say hello to the Octocat on GitHub's 404 page.
- Observe that the URL you tried to open is `https://github.com/ineo6/git-master/blob/master/inject.js` instead of `https://github.com/ineo6/git-master/blob/master/views/inject.js`.

Microsoft Edge v80.0.361.111 on WIndows 10 x64.
Feel free to ask for any further clarification you may need.

**Comment by ineo6** [comment]
Thanks. I will check it as soon as possible.&nbsp;

**Comment by ineo6** [comment]
I found the problem. Now you can disable "Lazy-load code tree" config. Next version will fix.

**Comment by ineo6** [comment]
`v1.2.0` fixed
