### ISSUE TITLE
Neither Gitmaster sidetab nor Dark theme works for gists.

### ISSUE THREAD

**Issue by mesajidiqbal** [ineo6/git-master#30]
It would be great if it would also work for gist.github.com (As gists are also repository only) and would provide all these great features for gists too.

At this moment I am using following three different extensions along with git-master to work with github:

1. github-dark-theme => https://github.com/poychang/github-dark-theme
* To apply dark theme on gists too (as git-master provides for repo)

2. better-gists => https://github.com/farskid/better-gists
* To add download/copy buttons to each gist file (as git-master provides for repo)

3. github-one-dark-vivid => https://github.com/ljosberinn/github-one-dark-vivid
* To apply vs code dark theme along with fira-code/Jetbrains-mono ligatures everywhere to make the code more readable and easy on eyes.

And still looking for an extension which can provide a side tab as git-master to explore all the gists :)

Would really be great if all these are combined in git-master itself...

**Comment by ineo6** [comment]
Thank you. This is a good idea. I will do this work as soon as possible.

**Comment by ineo6** [comment]
Dark mode and  copy button added in `1.9.0`

**Comment by mesajidiqbal** [comment]
That's really great work in a very short span of time !!! 👍

Just wanted to add a few suggestions for further improvements:

- Adding a **Download** button for individual files (similar to one provided by git-master in repositories)
    - The download button provided by default from GitHub, downloads all the files (similar to GitHub options for repositories) and does not provide an option to download individual files, so adding a 'download' button along with 'copy' button (similar to the option requested in (issue-32)[https://github.com/ineo6/git-master/issues/32] here) will certainly be a great feature, which would also provide a uniform user experience across both repository page and gist page.
    - The 'copy' option would not work well with 'Jupyter Notebooks (.ipynb)', (because it would display the contents in JavaScript format) so adding a 'download' button along with 'copy' would really work well in those situations (assume the gist repo contains 100 .ipynb files and each of 3mb, and one needs to download 1 file only, so downloading using default GitHub button (300mb) is also not a good option)

Just created a sample for the expected UI (Please find below) 😊:
![gist](https://user-images.githubusercontent.com/44871521/91640247-bccfec80-ea39-11ea-883d-ec8cb1df06c6.png)


Also, you can keep the side-tab on Gist page (similar to GitHub repo page), providing the user a slightly different functionality:
 - On Gist main page, it would provide the user options to navigate through different gist repos (similar to GitHub) providing an anchor link for each gist repo page and displaying all the files under it if you expand the icon
 - After opening a particular gist, the side-tab would work as a cluster of anchor links for each of the files in that gist (i.e. when you click on a filename in side-tab, it scrolls down/up to that particular file on the same page)
Consider how great and fast the navigation would become if a gist has 100 files in it.

**Comment by ineo6** [comment]
Now side bar works for gist and download button for single file is also added.

**Comment by mesajidiqbal** [comment]
Thanks man👍
You're really awesome!
I think this issue can be closed now.
