### ISSUE TITLE
会支持 Safari 吗？

### ISSUE THREAD

**Issue by hzb** [ineo6/git-master#33]

**Comment by ineo6** [comment]
计划支持的，前段时间有消息`Safari`也要支持`web extensions`标准，另外也支持`Chrome`扩展转换，保持观望中。

**Comment by hzb** [comment]
Cool

**Comment by ineo6** [comment]
同步下信息，目前代码层面支持了`Safari  14`，不过因为暂时不考虑开通付费开发者账号，所以无法上架市场。

**Comment by hzb** [comment]
Good job!

不过不能上市场有点可惜。

**Comment by zzswang** [comment]
> 同步下信息，目前代码层面支持了`Safari 14`，不过因为暂时不考虑开通付费开发者账号，所以无法上架市场。

工具很好用 可以考虑上架。

如果需要的话，可以提供付费的开发者账号
