### ISSUE TITLE
gitlab下不会自动加载树，必须每次去disable 、enable gitlab

### ISSUE THREAD

**Issue by alzuobaba** [ineo6/git-master#34]
目前只在gitlab下发现了，github 无影响

**Comment by ineo6** [comment]
能否外网访问测试？`gitlab`安装版本号是什么？

在这两个网站里测试正常：https://gitlab.com/explore , https://git.lug.ustc.edu.cn/explore

**Comment by ineo6** [comment]
Closed by no response.
