### ISSUE TITLE
How To Contact Me && Group

### ISSUE THREAD

**Issue by ineo6** [ineo6/git-master#35]
## WeChat Group

![git-master-qr](https://user-images.githubusercontent.com/3783838/91822075-d6577b00-ec69-11ea-903a-a2dd3ae921c1.jpg)

## Or Chat Room

[![Gitter](https://badges.gitter.im/ineo6/GitMaster.svg)](https://gitter.im/ineo6/GitMaster?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by HSA2020UX** [comment]
> ## WeChat Group
> ![git-master-qr](https://user-images.githubusercontent.com/3783838/91822075-d6577b00-ec69-11ea-903a-a2dd3ae921c1.jpg)
> 
> ## Or Chat Room
> [![Gitter](https://camo.githubusercontent.com/9af97a320ce9c6bbea24d903e4af68c776f59f3d4afa17a5add8126d2469c4c2/68747470733a2f2f6261646765732e6769747465722e696d2f696e656f362f4769744d61737465722e737667)](https://gitter.im/ineo6/GitMaster?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
