### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by lonix1** [ineo6/git-master#38]
Is firefox support planned?

**Comment by ineo6** [comment]
Firefox was released before, but it was been canceled because code review was passed.
So I need spend some times to fix it.

**Comment by Darkle** [comment]
Is there any progress on this?

**Comment by ineo6** [comment]
Sorry, still not. Maybe next month.  I wii try.

**Comment by ineo6** [comment]
Firefox available.

https://addons.mozilla.org/zh-CN/firefox/addon/git-master/
