### ISSUE TITLE
gitlab多层group时路径解析错误

### ISSUE THREAD

**Issue by HaoQChen** [ineo6/git-master#39]
git master版本`v1.11.0`

gitlab版本`GitLab Community Edition 11.2.1`

Chrome版本`77.0.3865.90 (Official Build) unknown (64-bit)`

|||
|:---:|:---|
|真正目录| `http://192.168.1.20/group1/group2/group3/project_name/blob/master/.clang-format`|
|git master出来目录|`http://192.168.1.20/group1/group2/group3/blob/master/.clang-format`|

后面少了project_name。

实际测试，如果group少于3个是可以正确解析的

**Comment by ineo6** [comment]
`1.11.1` fix this problem.
