### ISSUE TITLE
[Bug] gitee 使用该插件会导致文件夹图标丢失

### ISSUE THREAD

**Issue by Vixb1122** [ineo6/git-master#41]

**Comment by ineo6** [comment]
需要提供下错误截图以及对应的gitea版本号方便排查，另外可以到 https://try.gitea.io 上面是否存在这个问题，我的测试是基于官方demo来处理

**Comment by Vixb1122** [comment]
@ineo6 是gitee啊，不是gitea
![image](https://user-images.githubusercontent.com/17810492/95643217-73ff5f00-0ae0-11eb-9365-93403b7f58dd.png)

**Comment by Vixb1122** [comment]
@ineo6 你直接区看gitee的任意一个项目就能复现

**Comment by ineo6** [comment]
Fixed in `1.11.4`
