### ISSUE TITLE
Gitlab路径生成错误

### ISSUE THREAD

**Issue by comeNie** [ineo6/git-master#44]
版本：  1.11.1
例如工程结构如下：
test
  | 
 test-dal
       |
      src/main/java/com.test
              |  
             AClass.java     BClass.java

  
通过导航访问AClass文件。 
 路径：  https://gitlab.com/xxxx/xxxx/xxxx/test/blob/master/test-dal/src/main/java/com/test/AClass.java  访问正常。
此时在通过导航方位BClass文件。
 https://gitlab.com/xxxx/xxxx/xxxx/test/blob/master/test-dal/src/main/java/com/test/blob/master/test-dal/src/main/java/com/test/BClass.java    
生成的访问路径错误。

**Comment by ineo6** [comment]
帮忙确认下 https://gitlab.com/rluna-database/nosql/mongodb/mongo/blob/master/buildscripts/idl/idl/bson.py 是否存在问题，我找了几个多级项目测试无法复现。

**Comment by comeNie** [comment]
上述地址没有问题。 我发生的路径是内部gitlab.  我新建一个示例。  路径：
https://gitlab.com/test-git-master/test-sub-git-mastert/sofa-boot/blob/master/sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ConsumerConfigContainer.java


通过导航。  访问：container 同级下文件。   RpcFilterContainer.java.      返回地址：  
https://gitlab.com/test-git-master/test-sub-git-mastert/sofa-boot/-/tree/master   地址路径也不对。

**Comment by ineo6** [comment]
`1.11.3`版本解决该问题，目前`Chrome`已发布，`Edge`仍在审核中。
