### ISSUE TITLE
GitLab Community Edition 13.5.2 项目首页不显示gm pin

### ISSUE THREAD

**Issue by w0080626** [ineo6/git-master#45]
RT，只有项目首页不显示gm pin，进入到项目任何一个二级页面都会正常显示；希望repo主修复一下；感谢！

**Comment by w0080626** [comment]
测试了下，，https://gitlab.com/rluna-database/nosql/mongodb/mongo  这个项目也有此问题；

**Comment by ineo6** [comment]
感谢返回，目前看是`1.11.2`发布引起的新问题，会尽快再次发布。

**Comment by ineo6** [comment]
`1.11.3`版本解决该问题，目前`Chrome`已发布，`Edge`仍在审核中。
