### ISSUE TITLE
Chrome下gitlab，左边小图标没出来

### ISSUE THREAD

**Issue by HaoQChen** [ineo6/git-master#46]
环境：

+ Ubuntu 1604
+ Chrome 77.0.3865.90
+ Gitlab Community Edition 11.2.1

现象：

没有左边的小图标出来、

![image](https://user-images.githubusercontent.com/13584792/98627264-c7b6cf80-234e-11eb-8540-e26887205141.png)

github正常

![image](https://user-images.githubusercontent.com/13584792/98626391-9d641280-234c-11eb-9f99-c80cb53926ab.png)

最近更新比较频繁，没有太注意情况。好像是1.11.2的时候就有点小问题，但点进某个文件小图标就出来了。1.11.3彻底没了

**Comment by ineo6** [comment]
方便发下访问地址吗？关键信息可以xxx替代，主要是想看地址格式。





------------------ 原始邮件 ------------------
发件人: HaoQChen <notifications@github.com&gt;
发送时间: 2020年11月10日 12:03
收件人: ineo6/git-master <git-master@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ineo6/git-master] Chrome下gitlab，左边小图标没出来 (#46)





 
环境：
  
Ubuntu 1604 

Chrome 77.0.3865.90 

Gitlab Community Edition 11.2.1 
 
现象：
 
没有左边的小图标出来、
 

 
github正常
 

 
最近更新比较频繁，没有太注意情况。好像是1.11.2的时候就有点小问题，但点进某个文件小图标就出来了。1.11.3彻底没了

**Comment by HaoQChen** [comment]
http://192.168.1.20/group_1/group_2/project_name

**Comment by HaoQChen** [comment]
![image](https://user-images.githubusercontent.com/13584792/98627186-8d4d3280-234e-11eb-96a8-f3f486130ea8.png)

这个信息不知道对你调试有没有用

**Comment by ineo6** [comment]
地址就足够了，主要是因为地址的判断规则调整了。





------------------ 原始邮件 ------------------
发件人: HaoQChen <notifications@github.com&gt;
发送时间: 2020年11月10日 12:16
收件人: ineo6/git-master <git-master@noreply.github.com&gt;
抄送: ineo6 <arklove@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ineo6/git-master] Chrome下gitlab，左边小图标没出来 (#46)

**Comment by HaoQChen** [comment]
可以了
