### ISSUE TITLE
gitee插件一直处于加载中

### ISSUE THREAD

**Issue by a471640241** [ineo6/git-master#49]
**缺陷描述**
简洁准确得描述问题。
打开gitee任意项目，插件一直无法加载代码树

**如何重现**
重现步骤:
打开gitee任意项目

**截图**
![image](https://user-images.githubusercontent.com/11511810/99221523-b4f33d80-281b-11eb-8511-452ae976e122.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea):  gitee
 - 浏览器和对应的版本:  QQ浏览器 10.6.1  Chrome  86.0.4240.183
 - GitMaster 版本: 1.11.4

**补充的环境信息**
额外可以补充说明的信息

**Comment by monsterhxw** [comment]
same issue

**Comment by yizhiliulangmao** [comment]
同样的问题+1

**Comment by ineo6** [comment]
临时解决方案：勾选“设置-懒加载”，`gitee`默认只能采用懒加载的形式，这里是没有兼容异常场景。

**Comment by ineo6** [comment]
Fixed in `1.11.5`.

禁用`gitee`全量加载模式
