### ISSUE TITLE
扩展图标上的 ? 是什么情况?

### ISSUE THREAD

**Issue by Beeta** [ineo6/git-master#5]
![image](https://user-images.githubusercontent.com/4686476/79755052-06e9e880-834b-11ea-9bc0-627eaaa72758.png)
如图

**Comment by ineo6** [comment]
图标是GitHub通知未设置的状态提示，如果在选项中设置了对应的`token`，就不会出现这个图标。

后续会优化这个显示，现在放的位置容易有歧义。

**Comment by Beeta** [comment]
问题是我已经添加了token了…

**Comment by ineo6** [comment]
是在树形控件位置的设置，还是在图标右键-选项出来的页面。

如果是在扩展选项里出现问题，检查下`Root URL`是否是`https://api.github.com/`，`Token`里输入是否正确（创建时是否有`notifications`权限）

**Comment by Beeta** [comment]
感谢, 原来在树形控件那里设置了还要在扩展选项里设置…已经改好来, 但还有一个问题, 这个扩展选项在我这(mac, edge浏览器) 宽度显示不全

![image](https://user-images.githubusercontent.com/4686476/79817816-de98d300-83b8-11ea-83c5-e985cfe6d049.png)
有空帮忙看下~~辛苦

**Comment by ineo6** [comment]
正在审核的版本改为新页面展示，`Edge`限制了弹窗的宽度，无法适配。

**Comment by ineo6** [comment]
`v1.2.0` 已发布
