### ISSUE TITLE
gitea项目点击路径下某个文件后，跳转页面中插件无法定位文件路径，仍显示在根路径

### ISSUE THREAD

**Issue by tgly307** [ineo6/git-master#50]
**缺陷描述**
简洁准确得描述问题。
在gitea项目中，在插件中点击某个子路径下文件，页面跳转至该文件页面，插件路径会回到根路径页面，无法定位到当前文件所在路径。
**如何重现**
重现步骤:
1、进入gitea项目页面，插件加载
2、任选一个存放于子路径的文件，跳转至该文件页面
3、插件重新加载后，回到根路径状态，未定位至当前文件

**预期描述**
简洁准确得预期结果。
插件能够定位至对应文件路径
**截图**
可以的话，添加相关截图能更准确说明问题。
![image](https://user-images.githubusercontent.com/25153311/99225592-43b78880-2823-11eb-9cda-3e2a9522328e.png)
通过点击插件内文件链接已经打开了`src/App.vue`文件，但插件回到了初始状态，未定位到对应文件路径

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea): Gitea1.12.4
 - 浏览器和对应的版本: chrome 86
 - GitMaster 版本: 1.11.4

**补充的环境信息**
额外可以补充说明的信息

**Comment by ineo6** [comment]
Fixed in `1.11.5`.
