### ISSUE TITLE
浏览大项目时出现的错误

### ISSUE THREAD

**Issue by i-curve** [ineo6/git-master#53]
**缺陷描述**

github上大的项目会显示Error: API limit exceeded

另外，如果页面长时间不同的话，会出现改页面卡死（有很大概率，但无法百分百确定是本插件问题）。
**如何重现**

重现步骤:
github上查看一个比较大的项目。目录无法正常显示。
我这出现问题的项目为140M

卡死问题： 有时候浏览器直接卡死，有时候是该页面卡死，页面无法滚动，鼠标无效。
**预期描述**
简洁准确得预期结果。

**截图**
![image](https://user-images.githubusercontent.com/40533808/102998843-f1286500-4562-11eb-8256-b908c6778e67.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea):  github
 - 浏览器和对应的版本:  谷歌最新（87.0.4280.88）
 - GitMaster 版本: 1.11.5

**补充的环境信息**
额外可以补充说明的信息

**Comment by ineo6** [comment]
出现`API limit exceeded`提示是没有配置`token`，接口限流了。

参考 [access-token](https://github.com/ineo6/git-master/blob/master/README.zh-CN.md#access-token)

另外方便的话可以把仓库地址也贴出来。

**Comment by i-curve** [comment]
恩, 我去设置看看
该仓库地址:
[https://github.com/shi-yang/jnoj](https://github.com/shi-yang/jnoj)
