### ISSUE TITLE
支持多级空文件目录合并

### ISSUE THREAD

**Issue by draymondgewade** [ineo6/git-master#55]
**缺陷描述**
不支持多级空间目录合并

**截图**
![image](https://user-images.githubusercontent.com/43830206/104797874-bc739a80-57fc-11eb-954e-3e8a66075d19.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea): GitHub, Gitlab, Gitee
 - 浏览器和对应的版本:  Chrome87 
 - GitMaster 版本: latest

**Comment by ineo6** [comment]
懒加载（仓库较大，gitlab都会自动启用）下不支持多级空目录合并，因为无法提前知道下级目录内容。

**Comment by draymondgewade** [comment]
> 懒加载（仓库较大，gitlab都会自动启用）下不支持多级空目录合并，因为无法提前知道下级目录内容。

设置未开启懒加载, Gitee环境也会有此情况, 同类型插件能够合并空目录

**Comment by ineo6** [comment]
之前`gitee`的`api`设置了分页，对于大仓库无法完整获取结构，所以采用了懒加载模式。

目前看接口是更新了支持，接下来会更换接口。

**Comment by ineo6** [comment]
`1.12.0`已修复，目前`Edge`版本仍在审核中。
