### ISSUE TITLE
Spring Boot 工程多级空目录合并

### ISSUE THREAD

**Issue by draymondgewade** [ineo6/git-master#56]
与同类型插件对比
本插件
![image](https://user-images.githubusercontent.com/43830206/104868572-ab529700-597e-11eb-88b3-9517f7f9edba.png)

同类型插件
![image](https://user-images.githubusercontent.com/43830206/104868558-a0980200-597e-11eb-8629-5c74e1bbaacd.png)

本插件其他体验都很好, 希望能够优化这个问题, 十分感谢

**Comment by ineo6** [comment]
为了区分问题，能提供下你访问的仓库地址吗？

**Comment by draymondgewade** [comment]
> 为了区分问题，能提供下你访问的仓库地址吗？

https://gitee.com/durcframework/SOP.git

**Comment by ineo6** [comment]
`1.12.0`已修复，目前`Edge`版本仍在审核中。
