### ISSUE TITLE
GitHub页面显示的GM图标特别大，占据大量页面

### ISSUE THREAD

**Issue by qlmlove** [ineo6/git-master#57]
**缺陷描述**
GitHub页面显示的GM图标特别大，占据大量页面，重启浏览器和电脑都没效果，现在我只能把浏览器窗口拖到非常宽才能正常浏览

**如何重现**
我也不知道如何重现，反正我的浏览器打开一直这样

**预期描述**
预期应该是和之前一样只占指甲盖大小的位置，现在都有鸡蛋大了

**截图**

截图如下
![image](https://user-images.githubusercontent.com/37925929/107868199-33b05300-6ebd-11eb-9d6b-1a4893f25ce9.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea): GitHub
 - 系统：Win10专业版（x64） 20H2，系统版本号：19042.804
 - 浏览器和对应的版本:  Google Chrome  90.0.4412.3（正式版本）dev （64 位）
 - GitMaster 版本: 1.12.0

**补充的环境信息**
额外可以补充说明的信息

**Comment by ineo6** [comment]
访问码云或者`Gitlab`是否还有问题呢？目前在怀疑`Chrome`最新版上有问题， `mac`上暂时只能看到88版本。

**Comment by qlmlove** [comment]
可能真的只是chrome开发者版的问题，码云和GitLab也同样的问题，另外在开发者工具的Console下有这么一行提示，你看看是不是更改之后的版本来修复：
[Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.

**Comment by ineo6** [comment]
好的，感谢反馈，我尝试下开发版本。

**Comment by qlmlove** [comment]
![image](https://user-images.githubusercontent.com/37925929/107879462-dabfd980-6f13-11eb-9f07-b4dbfcb15ffd.png)
手动设置一遍这两个属性之后就正常了，我暂时用油猴给这个插件强制加了一遍style，临时能用了，但是奇怪的是88版本也是这样被删除线标记，但是CSS Computed的结果都是正常的25px，90版本的是svg图的大小256，另外上边我给的那个提示好像也没用，只在GitHub页面存在，换其他git就不存在了，应该与这个插件无关

**Comment by yi-Xu-0100** [comment]
个人更新为 edge dev 最新版开始出现此问题，Microsoft Edge 版本 90.0.796.0 (官方内部版本) dev (64 位)

**Comment by ineo6** [comment]
`1.12.1`已修复该问题。`Chrome`上已经更新，`Edge`上仍在审核（上个版本至今还未审核过）。

**Comment by yi-Xu-0100** [comment]
emmm, 我试试直接安装 chrome 版吧，谢谢！@ineo6

**Comment by ineo6** [comment]
新版本终于在`Edge`通过了。
