### ISSUE TITLE
没有通知

### ISSUE THREAD

**Issue by yi-Xu-0100** [ineo6/git-master#59]
**缺陷描述**

我更换了新的 token，好像就没有收到通知了。新的 token 格式不一样，但感觉应该没有影响。

![image](https://user-images.githubusercontent.com/25523606/114264232-4c03a080-9a1c-11eb-92c4-5ff4fde712b9.png)

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

**环境信息 (请完善下面的信息):**
 - github
 - edge dev
 - GitMaster 版本: 1.13.0

希望能够提供检查 token 的按钮，帮助确认 token 有效性。

**Comment by yi-Xu-0100** [comment]
@ineo6 我一直收不到通知……连图标上的数字标都不显示了，有什么能检查的吗？我试着重置了好几个 token 了。

**Comment by ineo6** [comment]
已确认该问题，会尽快发布新版本解决该问题。

**Comment by yi-Xu-0100** [comment]
@ineo6 v1.14.0 测试通知有效! 感谢！

**Comment by yi-Xu-0100** [comment]
@ineo6 你好，我最近使用了 firefox 上的插件，同样没有图标上的数字，在同一时间下，我的 edge 上能够看到图标上的提示数字，但是 firefox 上没有。。。二者我都设置的是同一个新版的 token，我现在没有旧版本的 token 用来测试。不知道是什么原因……

**Comment by ineo6** [comment]
不好意思，才注意到有新的问题，`firefox`版本内部报错，导致`token`配置后还是无法获取到通知，稍后会更新。

**Comment by yi-Xu-0100** [comment]
@ineo6 非常感谢，等待更新！😁

**Comment by yi-Xu-0100** [comment]
@ineo6 你好，我这边使用火狐浏览器，看起来已经能够收到通知了，但是似乎还是没有角标提示？（早上发现的

**Comment by yi-Xu-0100** [comment]
好像没有问题了
