### ISSUE TITLE
又抓到一个奇怪的 bug，应用在所有网站会导致部分图标不显示

### ISSUE THREAD

**Issue by geekyouth** [ineo6/git-master#6]
# 我的 cdh 后台有些图标不显示，后来才发现是 这个插件导致的，修改如下即可解决：
![image](https://user-images.githubusercontent.com/12899262/80551729-0dd1c480-89f7-11ea-9963-4b23bd12c73c.png)

---------------------------------------------------------
# 问题复现：
# 1-设置为点击时调用该插件，可正常显示图标：
![image](https://user-images.githubusercontent.com/12899262/80552040-019a3700-89f8-11ea-86c4-ebf874b6a589.png)

![image](https://user-images.githubusercontent.com/12899262/80552073-2098c900-89f8-11ea-9ad5-e70c9a40179f.png)

# 2-设置为在所有网站使用，打开某些网页无法显示部分元素：
![image](https://user-images.githubusercontent.com/12899262/80552121-3ad2a700-89f8-11ea-8793-e70d1c5d7dcc.png)
![image](https://user-images.githubusercontent.com/12899262/80552136-41f9b500-89f8-11ea-8316-ea72a4550599.png)

**Comment by ineo6** [comment]
不算奇怪的`bug`，我的一个大锅。这是因为注入的`css`污染了页面的样式。Thanks，尽快发布新版本。

**Comment by geekyouth** [comment]
懒加载导致的部分仓库文件跳转404 尚未解决哟

**Comment by ineo6** [comment]
使用的是`1.2.0`版本吗，浏览的仓库地址发下。

**Comment by ineo6** [comment]
`1.3.0`解决`icon`污染问题，新版本的文件图标也更新了样式。
