### ISSUE TITLE
chrome插件启动后会发出提示音

### ISSUE THREAD

**Issue by nashaofu** [ineo6/git-master#60]
**缺陷描述**
chrome 插件启动后有新消息一直会发出提示音

**如何重现**
重现步骤:
1. mac上，chorme 89
2. 安装插件后，启用插件会立马有提示音，并且间隔一段时间就会发出提示音

**预期描述**
不要一直产生提示音，提示一次之后就停止掉，或者提供关闭功能

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea):与平台无关
 - chrome 89.0.4389.128 
 - GitMaster 版本:最新版

**Comment by ineo6** [comment]
是否启用了`GitHub`通知功能，如果是的话可能是新通知导致的语音提示。

可以到扩展-选项里关闭“通知声效”选项。除此之外扩展中再也没有播放声音的逻辑。

**Comment by nashaofu** [comment]
谢谢，已解决。前几天电脑一直发出提示音，我以为电脑坏了！排查了很久才找到原来是这个插件[旺柴]


-------- 原始邮件 --------
发件人： ineo6 ***@***.***>
日期： 2021年4月21日周三 19:31
收件人： ineo6/git-master ***@***.***>
抄送： nashaofu ***@***.***>, Author ***@***.***>
主 题： Re: [ineo6/git-master] chrome插件启动后会发出提示音 (#60)

是否启用了GitHub通知功能，如果是的话可能是新通知导致的语音提示。

可以到扩展-选项里关闭“通知声效”选项。除此之外扩展中再也没有播放声音的逻辑。

―
