### ISSUE TITLE
希望能够支持切换分支

### ISSUE THREAD

**Issue by DongyunLee** [ineo6/git-master#61]
### 缺陷描述
现在即使不在master分支，也会固定显示“master”

### 如何重现
重现步骤:
1. 进入某仓库
2. 切换分支
      - 或切换pr

### 预期描述
- 在每个分支中，显示当前分支的内容；
- 在pr中，显示pr所在分支的内容

### 截图
![image](https://user-images.githubusercontent.com/22876282/116511978-e1969f80-a8f9-11eb-91df-616b59e8abb3.png)

### 环境信息 (请完善下面的信息):
 - 平台(GitHub, GitLab, Gitee, Gitea): 私有 Gitlab
 - 浏览器和对应的版本: **Microsoft Edge** 版本 `90.0.818.46 (官方内部版本) (64 位)`
 - GitMaster 版本: 1.11.5

**Comment by ineo6** [comment]
目前最新版本为`1.14.0`，尝试升级到最新版本再尝试下。
