### ISSUE TITLE
移除 Github md code 模块自动添加复制代码的行为

### ISSUE THREAD

**Issue by crown3** [ineo6/git-master#64]
**缺陷描述**
Github 的 所有md文件都自带了 copy icon，由于该插件添加了自己的图标按钮，导致复制按钮跟 github 自己的 icon 重叠冲突（虽然功能没什么影响，但是看着很奇怪）

**如何重现**
重现步骤: 打开任意带有 code 模块的md文件即可即可看到下面截图展示

**预期描述**
移除 github 下面添加复制按钮的相关代码

**截图**
![image](https://user-images.githubusercontent.com/19649900/120154202-36437800-c222-11eb-8f50-fcd1375466ff.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea): Github
 - 浏览器和对应的版本: Chrome, Version 91.0.4472.77 (Official Build) (x86_64)
 - GitMaster 版本: v1.14.0

**Comment by ineo6** [comment]
`1.16.0` fixed.
