### ISSUE TITLE
Github Release 加速链接异常

### ISSUE THREAD

**Issue by JadynWong** [ineo6/git-master#65]
**Describe the bug**
Github release 加速下载，多项Assets时，连接叠加

**To Reproduce**
https://download.fastgit.org/EasyAbp/AbpHelper.GUI/releases/download/v1.3.2/AbpHelper-1.3.2.AppImage/EasyAbp/AbpHelper.GUI/releases/download/v1.3.2/AbpHelper-1.3.2.dmg
当Assets越多，叠加连接越长

**Expected behavior**
https://download.fastgit.org/EasyAbp/AbpHelper.GUI/releases/download/v1.3.2/AbpHelper-1.3.2.dmg

**Screenshots**
![image](https://user-images.githubusercontent.com/13699353/121108550-8763f500-c83c-11eb-969b-bdc1124c5cb1.png)

**Context (please complete the following information):**
 - Platform(GitHub, GitLab, Gitee, Gitea): Github
 - Browser and Version: Edge 91.0.864.41
 - GitMaster Version: 1.14.0

**Additional context**
https://github.com/ineo6/git-master/blob/5e85d0d5f84dfa705dd010527be9be76bbfbd9e2/src/ContentScript/feature/mirror/index.ts#L108-L164

`downloadMirror[0].url`和`downloadMirror[1].url`循环追加前面的链接

**Comment by ineo6** [comment]
`1.16.0` fixed.
