### ISSUE TITLE
这是一个求助贴.

### ISSUE THREAD

**Issue by midgithub** [ineo6/git-master#66]
和git-master的主体功能无关. 本身正常使用中.下面只是一个请求,希望有时间的时候帮忙下

看上了gm的良好的ui设计和交互.希望能够把部分代码抽离出来,做成点击一个侧边按钮 能够打开一个内嵌iframe的侧边栏,也可以调节大小,然后现在侧边栏里的搜索和目录树也可以独立出来开源变成一个具备简单搜索功能的目录树管理结构,能够新建和修改目录内容. 这两个控件是我觉得自由度都会很高.像设置面板也可以保留这么个机制.会是一个不错的开源的前端ui控件展示共用组件,目前看了一些网站或者chrome插件的布局设计都没有git-master的合理和方便.要不就是弹出后会遮挡本来的边框.

目前我个人是打算分离上面说的这几个部分代码. 希望可以的话,原作者直接分离另建立仓库是最快的.也是另外的两个开源的组件了.

基于这个ui设计的壳,可以拓展很多类型的组件,比如 侧边书签栏等

**Comment by ineo6** [comment]
抱歉，回复晚了。

目前觉得独立出来其实用处不大，而且花费的时间比直接使用代码的时间多多了。建议你可以先分离自己用的逻辑，或许你就可以先分离，然后就有余力封装出来。

PS：如果有问题我们也可以交流下，看能不能给你提供必要的信息。
