### ISSUE TITLE
Content features configurable

### ISSUE THREAD

**Issue by icefed** [ineo6/git-master#68]
**缺陷描述**

1. Code snippet copy button, 这个功能 Github 已经提供，GitMaster 中的该功能可以删除
2. download、mirror、reposize这几个功能其他的扩展也有提供（Enhanced GitHub），功能重复且不可关闭

总体来说 GitMaster 是专注于 GitTree 的扩展，其他的 feature 可以单独做个扩展来使用。这些 Feature 放到 GitMaster 里最好是能提供开关给用户来决定是否关闭。

GitMaster 是个很好用的扩展，但是因为这几个功能和其他扩展冲突我不得不关掉 GitMaster，让我很是难受。

**Comment by ineo6** [comment]
十分感谢你的回复，我会好好考虑下的。

**Comment by ineo6** [comment]
添加了“GitHub 文件列表增强”选项用于关闭，默认是开启的。
