### ISSUE TITLE
Error: API limit exceeded

### ISSUE THREAD

**Issue by ilaipi** [ineo6/git-master#69]
**缺陷描述**
简洁准确得描述问题。
今天还没操作几次呢，突然提示这个

**如何重现**
重现步骤:
不知道哪里有说明

**预期描述**
简洁准确得预期结果。
之前用一天也没这个问题

**截图**
可以的话，添加相关截图能更准确说明问题。
![image](https://user-images.githubusercontent.com/1689135/131235686-067a39b2-aa9f-4c12-8913-173c3c577815.png)

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea):  GitHub
 - 浏览器和对应的版本:  chrome latest
 - GitMaster 版本: v1.16.0

**补充的环境信息**
额外可以补充说明的信息

**Comment by ineo6** [comment]
这种情况下需要设置 GitHub access token，可以点击齿轮设置。
