### ISSUE TITLE
Azure DevOps support?

### ISSUE THREAD

**Issue by mashirozx** [ineo6/git-master#73]
是否可以考虑支持 [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/)，类似 Gitlab，有公有版和私人部署版

**Comment by ineo6** [comment]
还没用过，等我研究下。



------------------ Original ------------------
From: Mashiro ***@***.***&gt;
Date: Sat,Nov 13,2021 11:53 AM
To: ineo6/git-master ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ineo6/git-master] Azure DevOps support? (Issue #73)

**Comment by ineo6** [comment]
Api文档：

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-4.1

1. 需要接入oauth
2. 界面内部已经有一个简单的树形展示

暂时不会考虑支持，需要调整的内容较多。

**Comment by mashirozx** [comment]
thanks
