### ISSUE TITLE
加个黑暗模式皮肤就更完美了

### ISSUE THREAD

**Issue by ngcly** [ineo6/git-master#9]
希望能加入黑暗模式的皮肤， 之前一直用octotree，挺喜欢它的皮肤黑暗模式的。但是最近不知道这玩意什么原因 ，经常左侧树状图加载不出来，而且速度又慢，还不支持gitee，心累，放弃那玩意了。

**Comment by ineo6** [comment]
曾经也计划过，我自己给自己否决了。哈哈，你给了我鼓励，这个也会加的。

**Comment by ngcly** [comment]
哇，厉害，回复这么快。  提一个小小的问题，感觉很奇怪，不知道是我这边的问题还是都这样。 就是gitee那边，每次点击一个类的时候总是会页面重新刷新加载，体验很不好。GitHub这边就特别丝滑，只会异步加载，就恨正常。

**Comment by ineo6** [comment]
Thanks. 你说的对，`gitee`现在就是页面刷新的形式，之前没解决好`pjax`（异步加载页面），最近总算找到处理的方法了，也会优化的。

**Comment by ngcly** [comment]
威武，给个大大的赞！ 期待更新
