### ISSUE TITLE
inject.js 加载时间过长

### ISSUE THREAD

**Issue by nian8** [ineo6/git-master#92]
**缺陷描述**
简洁准确得描述问题。
加载 oschina.net 时，会加载 chrome-extension://klmeolbcejnhefkapdchfhlhhjgobhmo/inject.js
并且耗时过长，堵塞加载

**如何重现**
重现步骤:

**预期描述**
简洁准确得预期结果。

**截图**
可以的话，添加相关截图能更准确说明问题。
<img width="876" alt="iShot2022-03-30_11 53 10" src="https://user-images.githubusercontent.com/13718159/160748113-18d1f486-7232-4f68-aca6-01d02beddc06.png">

**环境信息 (请完善下面的信息):**
 - 平台(GitHub, GitLab, Gitee, Gitea):
 - 浏览器和对应的版本:  Chrome 
 - GitMaster 版本: 

**补充的环境信息**
额外可以补充说明的信息

**Comment by nian8** [comment]
<img width="858" alt="iShot2022-03-30_11 56 21" src="https://user-images.githubusercontent.com/13718159/160748425-969093db-1bda-4439-b0b8-a2f48fba5c9f.png">

**Comment by ineo6** [comment]
方便提供下访问的url吗？ 另外是否把 oschina.net 设置了启用。

**Comment by nian8** [comment]
url: https://www.oschina.net/

**Comment by nian8** [comment]
不清楚是否和电脑环境有关，在另外一台电脑上正常

**Comment by nian8** [comment]
不是插件原因
