### ISSUE TITLE
请仅在访问 github 时加载文件

### ISSUE THREAD

**Issue by mtgq** [ineo6/git-master#95]
请在网页加载 gihub 或 gitee 时启用扩展。

**Comment by ineo6** [comment]
目前为了支持标记私有部署的站点，采用了在所有页面默认启用的方式。

如果实在不想，可以尝试在扩展页面操作“有权访问的网站”。

另外也可以把遇到的问题描述下。

**Comment by mtgq** [comment]
> 目前为了支持标记私有部署的站点，采用了在所有页面默认启用的方式。
> 
> 如果实在不想，可以尝试在扩展页面操作“有权访问的网站”。
> 
> 另外也可以把遇到的问题描述下。

好的，我去操作下。具体表现是：在调试某个网页时候发现多加载了个js，最后发现是扩展的 js
